In [1]:
import torch

In [2]:
scalar = torch.tensor(7)
scalar.ndim

0

In [3]:
vector = torch.tensor([1, 2])
vector.ndim

1

In [4]:
matrix = torch.tensor([[1, 2], [3, 4]])
matrix.ndim

2

In [5]:
tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor.ndim

3

In [16]:
import numpy as np

data = torch.tensor(10)
print(data)

data = np.random.randn(2,3)
data = torch.tensor(data)
print(data)

data = [[10.0, 11.0, 12.0], [13.0, 14.0, 15.0]]
data = torch.tensor(data)
print(data)

tensor(10)
tensor([[ 1.3010, -0.2458,  2.1554],
        [ 0.7967, -0.1847, -3.0264]], dtype=torch.float64)
tensor([[10., 11., 12.],
        [13., 14., 15.]])


In [14]:
data = torch.Tensor(2,3)
print(data)

data = torch.Tensor([10])
print(data)

data=  torch.Tensor([10,20])
print(data)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([10.])
tensor([10., 20.])


In [17]:
data = torch.IntTensor(2,3)
print(data)

data=  torch.IntTensor([2.5, 3.0])
print(data)

data = torch.ShortTensor()
data = torch.LongTensor()
data = torch.FloatTensor()
data = torch.DoubleTensor()

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([2, 3], dtype=torch.int32)


In [18]:
torch.cuda.is_available()

True

In [19]:
print(torch.__version__)

2.6.0+cu126


In [26]:
# 在指定区间按照步长生成元素 [start, end, step)
data = torch.arange(0, 50, step=1)
print(data)
# 在指定区间按照元素个数生成元素 [start, end, num]
data = torch.linspace(0, 50, 20)
print(data)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
tensor([ 0.0000,  2.6316,  5.2632,  7.8947, 10.5263, 13.1579, 15.7895, 18.4211,
        21.0526, 23.6842, 26.3158, 28.9474, 31.5789, 34.2105, 36.8421, 39.4737,
        42.1053, 44.7368, 47.3684, 50.0000])


In [32]:
seed = torch.random.initial_seed()
print(seed)

torch.random.manual_seed(222)
seed = torch.random.initial_seed()
print(seed)

data = torch.randn(2,3)
print(data)

222
222
tensor([[-0.4248,  1.1523, -2.1342],
        [ 0.5376,  1.0892, -2.2787]])


In [34]:
data  = torch.ones(2,3)
print(data)

data = torch.ones_like(data)
print(data)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [35]:
data = torch.zeros(2,3)
print(data)

data = torch.zeros_like(data)
print(data)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [36]:
data = torch.full([2,3],7)
print(data)

data = torch.full_like(data, 9)
print(data)

tensor([[7, 7, 7],
        [7, 7, 7]])
tensor([[9, 9, 9],
        [9, 9, 9]])


In [38]:
data = torch.full([2,3],10)
print(data.dtype)

data = data.type(torch.DoubleTensor)
print(data.dtype)

data = data.type(torch.IntTensor)
data = data.type(torch.LongTensor)
data = data.type(torch.FloatTensor)

torch.int64
torch.float64


In [39]:
data = torch.full([2,3],10)
print(data.dtype)

data = data.double()
print(data.dtype)

data = data.int()
data = data.long()
data = data.float()

torch.int64
torch.float64


In [ ]:
data_tensor = torch.tensor([2,3,4])
data_numpy = data_tensor.numpy()
print(type(data_tensor))
print(type(data_numpy))

print(data_tensor)
data_numpy[0] = 20
print(data_tensor)

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([2, 3, 4])
tensor([20,  3,  4])


In [42]:
data_tensor = torch.tensor([2,3,4])
data_numpy = data_tensor.numpy().copy()
print(type(data_tensor))
print(type(data_numpy))

print(data_tensor)
data_numpy[0] = 20
print(data_tensor)

<class 'torch.Tensor'>
<class 'numpy.ndarray'>
tensor([2, 3, 4])
tensor([2, 3, 4])


In [45]:
data_numpy = np.array([2,3,4])
print(data_numpy)

data_tensor = torch.from_numpy(data_numpy)
print(data_tensor)

print(data_numpy)
data_tensor[0] = 10
print(data_numpy)


[2 3 4]
tensor([2, 3, 4])
[2 3 4]
[10  3  4]


In [49]:
data_numpy = np.array([2,3,4])
print(data_numpy)

data_tensor = torch.from_numpy(data_numpy.copy())
print(data_tensor)

print(data_numpy)
data_tensor[0] = 10
print(data_numpy)

[2 3 4]
tensor([2, 3, 4])
[2 3 4]
[2 3 4]


In [50]:
data_numpy = np.array([2,3,4])
print(data_numpy)

data_tensor = torch.tensor(data_numpy)
print(data_tensor)

print(data_numpy)
data_tensor[0] = 10
print(data_numpy)

[2 3 4]
tensor([2, 3, 4])
[2 3 4]
[2 3 4]


In [51]:
data = torch.tensor([2,])
print(data.item())

data =  torch.tensor(2)
print(data.item())

2
2


In [52]:
data = torch.randint(0,10,[2,3])
print(data)

new_data = data.add(10)
print(new_data)

data.add_(10)
print(data)

print(data.neg())

tensor([[9, 6, 0],
        [4, 8, 3]])
tensor([[19, 16, 10],
        [14, 18, 13]])
tensor([[19, 16, 10],
        [14, 18, 13]])
tensor([[-19, -16, -10],
        [-14, -18, -13]])


In [ ]:
data1 = torch.tensor([[1, 2], [3, 4]])
data2 = torch.tensor([[5, 6], [7, 8]])

data = torch.mul(data1, data2)
print(data)

data = data1 * data2
print(data)

tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])
